package gov.psn.wpintegration.common;

public class DatabaseQueries {
	
	public static String getGpoOfPensioners ="SELECT DISTINCT\r\n"
			+ "						    F.PPO_NO AS PPO_NUMBER,\r\n"
			+ "						    B.EMPLOYEE_ID,\r\n"
			+ "						    INITCAP(B.NAME_EN) AS NAME_EN,\r\n"
			+ "						    D.SRVC_CAT_ID AS Service_Category_ID,\r\n"
			+ "						    INITCAP(D.SRVC_CAT_NAME_EN) AS Service_Category_NAME_EN,\r\n"
			+ "						    E.TREAS_CODE AS Treasury_ID,\r\n"
			+ "						    INITCAP(E.TREAS_NAME_EN) AS TREAS_NAME_EN,\r\n"
			+ "						    A.BUDGET_HEAD AS GPO_Budget_HeadId,\r\n"
			+ "						    A.GPO_APRV_DATE AS Issuance_Date,\r\n"
			+ "						    C.DOR AS Date_of_Retirement,\r\n"
			+ "						    A.DCRG_SHARE_AMT,\r\n"
			+ "						    NULL AS Deduction_Recovery_Amount,\r\n"
			+ "						    NULL AS Deduction_Recovery_Head,\r\n"
			+ "						    A.TOTAL_DCRG_AMT - nvl(A.DCRG_SHARE_AMT,0) AS Net_Payable_Amount,\r\n"
			+ "						    N.ACCOUNT_NO,\r\n"
			+ "						    O.IFSC_CODE,\r\n"
			+ "						    B.EMPLOYEE_CODE,\r\n"
			+ "						    A.GPO_NO,\r\n"
			+ "						    DC.DMS_DOC_ID,\r\n"
			+ "						    DC.DOC_TYPE_ID,\r\n"
			+ "						    DC.DOC_TYPE_NAME,\r\n"
			+ "						    ( gh.major_head_code\r\n"
			+ "						      || '-'\r\n"
			+ "						      || gh.sub_major_head_code\r\n"
			+ "						      || '-'\r\n"
			+ "						      || gh.minor_head_code\r\n"
			+ "						      || '-'\r\n"
			+ "						      || gh.sub_minor_head_code\r\n"
			+ "						      || '-'\r\n"
			+ "						      || gh.group_sub_head_code )           GPO_Budget_Head,			                  \r\n"
			+ "			             case when DE.IS_DE = 1 then 'Y' else 'N' end as is_de,\r\n"
			+ "			             bh.REF_NO,\r\n"
			+ "			             '' as Bill_Inner_DOC_ID,\r\n"
			+ "			                 '' as Bill_Outer_DOC_ID,\r\n"
			+ "			                 '' as Bill_Schedule_DOC_ID,\r\n"
			+ "			                  B.PENSIONER_ID\r\n"
			+ "						FROM\r\n"
			+ "						PSN.PSN_PERSONAL_DTLS B \r\n"
			+ "						inner join    PSN.PSN_GPO A ON A.PENSIONER_ID = B.PENSIONER_ID\r\n"
			+ "						INNER JOIN\r\n"
			+ "						    PSN.PSN_PPO F ON A.PPO_NO = F.PPO_NO\r\n"
			+ "						INNER JOIN\r\n"
			+ "						    PSN.PSN_SERVICE_DTLS C ON C.PENSIONER_ID = B.PENSIONER_ID\r\n"
			+ "						INNER JOIN\r\n"
			+ "						    MDM.MST_SRVC_CAT D ON D.SRVC_CAT_ID = C.SRVC_CAT_ID\r\n"
			+ "						LEFT JOIN\r\n"
			+ "						    MDM.MST_TREASURY E ON E.TREAS_CODE = F.TREASURY_CODE\r\n"
			+ "						INNER JOIN\r\n"
			+ "						    PSN.PSN_BANK_ACC_DTLS N ON N.PENSIONER_ID = B.PENSIONER_ID\r\n"
			+ "						LEFT JOIN\r\n"
			+ "						    PSN.PSN_DOC DC ON DC.PENSIONER_ID = C.PENSIONER_ID AND DC.DOC_TYPE_ID = 34\r\n"
			+ "						INNER JOIN\r\n"
			+ "						    MDM.MST_BANK_BRANCH O ON O.BANK_BRANCH_ID = N.BANK_BRANCH_ID\r\n"
			+ "						INNER JOIN mdm.mst_sub_group_head gh ON gh.budget_head_id = A.BUDGET_HEAD\r\n"
			+ "						left join PSN.BILL_HEADER BH on A.GPO_NO = Bh.SANCTION_NO\r\n"
			+ "						left join PSN.PSN_EMP_DE DE on DE.Employee_id = B.employee_id"
			+ "			WHERE\r\n"
			+ "			    A.IS_ACTIVE =?0";
	
	public static String getCpoOfPensioners = "SELECT DISTINCT\r\n"
			+ "			                           A.PPO_NO AS PPO_NUMBER,\r\n"
			+ "			                           B.EMPLOYEE_ID,\r\n"
			+ "			                           INITCAP(B.NAME_EN) AS Employee_Name,\r\n"
			+ "			                           G.SRVC_CAT_ID AS Service_Category_ID,\r\n"
			+ "			                           INITCAP(G.SRVC_CAT_NAME_EN) AS Service_Category_NAME_EN,\r\n"
			+ "			                           D.DEPT_ID AS Department_ID,\r\n"
			+ "			                           INITCAP(D.DEPT_NAME_EN) AS Department_NAME_EN,\r\n"
			+ "			                           F.TREAS_CODE AS Treasury,\r\n"
			+ "			                           INITCAP(F.TREAS_NAME_EN) AS Treasury_Name,\r\n"
			+ "			                           A.BUDGET_HEAD AS CPO_Budget_HeadId,\r\n"
			+ "			                           A.CPO_APRV_DATE AS Issuance_Date,\r\n"
			+ "			                           C.DOR AS Date_of_Retirement,\r\n"
			+ "			                           A.CMUT_AMT AS Net_Payable_Amount,\r\n"
			+ "			                           N.ACCOUNT_NO,\r\n"
			+ "			                           O.IFSC_CODE,\r\n"
			+ "			                           B.EMPLOYEE_CODE,\r\n"
			+ "			                           A.CPO_NO,\r\n"
			+ "			                           DC.DMS_DOC_ID,\r\n"
			+ "			                           DC.DOC_TYPE_ID,\r\n"
			+ "			                           DC.DOC_TYPE_NAME,\r\n"
			+ "			                            ( gh.major_head_code\r\n"
			+ "			                             || '-'\r\n"
			+ "			                             || gh.sub_major_head_code\r\n"
			+ "			                             || '-'\r\n"
			+ "			                             || gh.minor_head_code\r\n"
			+ "			                             || '-'\r\n"
			+ "			                             || gh.sub_minor_head_code\r\n"
			+ "			                             || '-'\r\n"
			+ "			                             || gh.group_sub_head_code )           CPO_Budget_Head,\r\n"
			+ "			                case when DE.IS_DE = 1 then 'Y' else 'N' end as is_de,\r\n"
			+ "			             bh.REF_NO,\r\n"
			+ "			             '' as Bill_Inner_DOC_ID,\r\n"
			+ "			                 '' as Bill_Outer_DOC_ID,\r\n"
			+ "			                 '' as Bill_Schedule_DOC_ID,\r\n"
			+ "			                  B.PENSIONER_ID\r\n"
			+ "			                     FROM\r\n"
			+ "			                       PSN.PSN_PERSONAL_DTLS B \r\n"
			+ "			                           INNER JOIN PSN.PSN_PPO H ON B.PENSIONER_ID = H.PENSIONER_ID\r\n"
			+ "			                        INNER JOIN\r\n"
			+ "			                           PSN.PSN_CPO A ON A.PPO_NO = H.PPO_NO\r\n"
			+ "			                        INNER JOIN\r\n"
			+ "			                           PSN.PSN_SERVICE_DTLS C ON C.PENSIONER_ID = B.PENSIONER_ID\r\n"
			+ "			                        INNER JOIN\r\n"
			+ "			                           MDM.MST_DEPARTMENT D ON D.DEPT_ID = C.DEPT_ID\r\n"
			+ "			                        LEFT JOIN\r\n"
			+ "			                           MDM.MST_TREASURY F ON F.TREAS_CODE = H.TREASURY_CODE\r\n"
			+ "			                        INNER JOIN\r\n"
			+ "			                           MDM.MST_SRVC_CAT G ON G.SRVC_CAT_ID = C.SRVC_CAT_ID\r\n"
			+ "			                        LEFT JOIN\r\n"
			+ "			                           PSN.PSN_PAY_CAL_DTLS M ON M.PENSIONER_ID = B.PENSIONER_ID\r\n"
			+ "			                        INNER JOIN\r\n"
			+ "			                           PSN.PSN_BANK_ACC_DTLS N ON N.PENSIONER_ID = B.PENSIONER_ID\r\n"
			+ "			                        LEFT JOIN\r\n"
			+ "			                           PSN.PSN_DOC DC ON DC.PENSIONER_ID = C.PENSIONER_ID AND DC.DOC_TYPE_ID = 34\r\n"
			+ "			                        INNER JOIN\r\n"
			+ "			                           MDM.MST_BANK_BRANCH O ON O.BANK_BRANCH_ID = N.BANK_BRANCH_ID\r\n"
			+ "			            INNER JOIN mdm.mst_sub_group_head gh ON gh.budget_head_id = A.BUDGET_HEAD            \r\n"
			+ "			            left join PSN.BILL_HEADER BH on A.cPO_NO = Bh.SANCTION_NO\r\n"
			+ "						left join PSN.PSN_EMP_DE DE on DE.Employee_id = B.employee_id						\r\n"
			+ "			                        WHERE\r\n"
			+ "			                           A.IS_ACTIVE =?0";
	

	public static String getEmployeeCode = "select EMPLOYEE_CODE from PSN_FAMILY_DTLS where EMP_ID = ?0";
}
